name: CI

on: [push, pull_request, workflow_dispatch]

# Cancels all previous workflow runs for pull requests that have not completed
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:

  phpTests:
    name: PHP ${{ matrix.php }} Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Shared Setup
        uses: ./.github/actions/shared-setup
        with:
          php-version: ${{ matrix.php }}

      - name: Run PHPStan Tests
        run: composer analyse

      - name: Start env container
        env:
          WP_ENV_PHP_VERSION: ${{ matrix.php }}
          # WP_ENV_CORE: 'WordPress/WordPress'
        run: |
          pnpm run env start
          pnpm run env run cli php --version
          pnpm run env run cli wp core version

      - name: Run Integration Tests
        run: |
          pnpm run composer test

  e2eTests:
    name: E2E Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Shared Setup
        uses: ./.github/actions/shared-setup
        with:
          php-version: 8.3
          playwright: true

      - name: Cache Playwright
        id: playwright-cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install Playwright and its dependencies
        if: ${{ steps.playwright-cache.outputs.cache-hit != 'true' }}
        shell: bash
        run: npx playwright install chromium webkit firefox --with-deps

      - name: Install just Playwright's dependencies
        if: ${{ steps.playwright-cache.outputs.cache-hit == 'true' }}
        shell: bash
        run: npx playwright install-deps

      - name: Start env container
        run: |
          pnpm run env start
          pnpm run env run cli php --version
          pnpm run env run cli wp core version

      - name: Run E2E Tests
        run: |
          pnpm run test:e2e

      - uses: daun/playwright-report-summary@1229105480a2a4bdd91598d8a146fbab41343fce # v3.11.0
        if: always()
        with:
          report-file: playwright-results.json
